import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'

const sora = Sora({ 
  subsets: ['latin'],
  weight: ["400", "500", "700"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
